"""Add Scenario Model

Revision ID: 45c199ad70c0
Revises: 9990cbcdde74
Create Date: 2025-12-07 18:19:27.525212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c199ad70c0'
down_revision: Union[str, None] = '9990cbcdde74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('dispatch_info', sa.Text(), nullable=True),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('narrative_key_points', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
