"""Initial migration to PostgreSQL

Revision ID: 0b15e24a1e17
Revises: 
Create Date: 2025-12-16 10:30:25.500164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b15e24a1e17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('issue_type', sa.Enum('clinical_error', 'typo', 'outdated', 'unclear', 'other', name='issue_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'fixed', 'invalid', name='issue_status'), server_default='pending', nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='issue_priority'), server_default='medium', nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reward_given', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('reward_type', sa.Enum('free_month', 'badge', 'credit', name='reward_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=True),
    sa.Column('brand_names', sa.String(), nullable=True),
    sa.Column('drug_class', sa.String(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('indications', sa.JSON(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('interactions', sa.Text(), nullable=True),
    sa.Column('dose_adult', sa.String(), nullable=True),
    sa.Column('dose_ped', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('side_effects', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_generic_name'), 'medications', ['generic_name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Float(), server_default='1000.0', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('dispatch_info', sa.Text(), nullable=True),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('narrative_key_points', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('has_lifetime_access', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('elo_rating', sa.Float(), server_default='1000.0', nullable=True),
    sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('semester_pass_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('plan_expiration', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(), nullable=True),
    sa.Column('back', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), server_default='1', nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcards')
    op.drop_table('exam_attempts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scenarios')
    op.drop_table('questions')
    op.drop_index(op.f('ix_medications_generic_name'), table_name='medications')
    op.drop_table('medications')
    op.drop_table('issues')
    # ### end Alembic commands ###
